name: Convert Markdown to HTML

on:
  push:
    paths:
      - 'md/*.md'

jobs:
  convert-md-to-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install marked

      - name: Convert MD to HTML
        run: |
          mkdir -p posts
          for file in md/*.md; do
            filename=$(basename "$file" .md)
            node -e "
              const fs = require('fs');
              const marked = require('marked');
              const path = require('path');

              try {
                const md = fs.readFileSync('$file', 'utf-8');
                const html = marked.parse(md);
                
                const title = (html.match(/<h1>(.*?)<\\/h1>/) || [])[1] || 'Untitled';
                
                const template = \`
                  <!DOCTYPE html>
                  <html lang='en'>
                  <head>
                    <meta charset='UTF-8'>
                    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
                    <title>\${title}</title>
                    <style>
                      body {
                        font-family: Arial, sans-serif;
                        line-height: 1.6;
                        color: #333;
                        max-width: 800px;
                        margin: 0 auto;
                        padding: 20px;
                      }
                      @media (max-width: 600px) {
                        body {
                          padding: 30px 15px 20px;
                        }
                      }
                      .home-link {
                        position: absolute;
                        top: 20px;
                        left: 20px;
                      }
                      h1, h2 {
                        color: #2c3e50;
                      }
                      a {
                        color: #3498db;
                        text-decoration: none;
                      }
                      a:hover {
                        text-decoration: underline;
                      }
                      blockquote {
                        border-left: 4px solid #3498db;
                        padding-left: 20px;
                        margin-left: 0;
                        font-style: italic;
                        color: #7f8c8d;
                      }
                    </style>
                  </head>
                  <body>
                    <a href='/' class='home-link'>Home</a>
                    \${html}
                  </body>
                  </html>
                \`;
                
                const outputPath = path.join('posts', '$filename.html');
                fs.writeFileSync(outputPath, template);
                console.log(\`Successfully created \${outputPath}\`);
              } catch (error) {
                console.error(\`Error processing \${file}: \${error.message}\`);
                process.exit(1);
              }
            "
          done

      - name: Update index.html
        run: |
          if [ ! -f index.html ]; then
            echo "index.html not found. Creating a basic version."
            cat > index.html <<EOL
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>My Blog</title>
          </head>
          <body>
            <h1>My Blog Posts</h1>
            <ul class="links">
              <!-- Blog post links will be added here -->
            </ul>
          </body>
          </html>
          EOL
          fi

          for file in posts/*.html; do
            if [ -f "$file" ]; then
              filename=$(basename "$file" .html)
              title=$(grep -oP '(?<=<title>).*(?=</title>)' "$file" || echo "$filename")
              if ! grep -q "$filename.html" index.html; then
                sed -i "/<ul class=\"links\">/a\        <li><a href=\"/posts/$filename.html\">$title</a></li>" index.html
              fi
            fi
          done

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add posts/*.html index.html
          git commit -m "Convert MD to HTML and update index" || echo "No changes to commit"
          git push || echo "No changes to push"
