name: Convert MD to HTML

on:
  push:
    paths:
      - 'md/**/*.md'

jobs:
  convert-md-to-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install marked

      - name: Convert MD to HTML
        run: |
          for file in md/*.md; do
            filename=$(basename "$file" .md)
            node -e "
              const fs = require('fs');
              const marked = require('marked');
              const md = fs.readFileSync('$file', 'utf-8');
              const html = marked.parse(md);
              const template = \`
              <!DOCTYPE html>
              <html lang="en">
              <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>$filename</title>
                <style>
                  body {
                    font-family: Arial, sans-serif;
                    line-height: 1.6;
                    color: #333;
                    max-width: 800px;
                    margin: 0 auto;
                    padding: 20px;
                  }
                  .home-link {
                    position: fixed;
                    top: 20px;
                    left: 20px;
                  }
                  @media (max-width: 768px) {
                    body {
                      padding: 40px 15px 20px;
                    }
                  }
                </style>
              </head>
              <body>
                <a href="/" class="home-link">Home</a>
                \${html}
              </body>
              </html>
              \`;
              fs.writeFileSync('posts/$filename.html', template);
            "
          done

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add posts/*.html
          git commit -m "Convert MD to HTML" || echo "No changes to commit"
          git push
