name: Convert Markdown to HTML and Deploy

on:
  push:
    paths:
      - 'md/*.md'
    branches:
      - main  # or your default branch name

jobs:
  convert-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install marked

      - name: Create converter script
        run: |
          cat > convert.js <<'EOL'
          # Your existing convert.js content here
          EOL

      - name: Convert MD to HTML
        run: |
          mkdir -p posts
          for file in md/*.md; do
            node convert.js "$file"
          done

      - name: Update index.html
        run: |
          # Your existing update index.html script here

      - name: Remove deleted HTML files
        run: |
          # Your existing remove deleted HTML files script here

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add posts/*.html index.html
          git commit -m "Convert MD to HTML and update index" || echo "No changes to commit"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes
        if: success()
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}